name: Publish UI to Vercel

on:
  workflow_dispatch:
    inputs:
      # Which branch are we publishing the deployments from?
      releaseType:
        description: 'Branch to prepare the deployments on'
        required: true
        type: choice
        options:
          - '🚧 prerelease (next branch)' # For prereleases (e.g., 0.1.0-next.1)
          - '🚀 production (main branch)' # For production releases (e.g., 1.0.0, 1.1.0, 1.1.1)

permissions:
  contents: read
  pull-requests: write
  deployments: write

env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_SCHEMA }}
  TWIN_VERCEL_ORG_ID: ${{ secrets.TWIN_VERCEL_ORG_ID }}

jobs:
  deploy:
    runs-on: ${{ github.event.repository.private && 'self-hosted' || 'ubuntu-latest' }}

    steps:
      # Set branch variable based on release type
      - name: Set target branch
        id: set-branch
        run: |
          INPUT="${{ github.event.inputs.releaseType }}"
          if [[ "$INPUT" == *"next"* ]]; then
            BRANCH="next"
          elif [[ "$INPUT" == *"main"* ]]; then
            BRANCH="main"
          else
            echo "Error: Unrecognized release type: $INPUT"
            exit 1
          fi
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "Using branch: $BRANCH"

      # Clone the repository to the runner
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Using GITHUB_TOKEN makes actions run as github-actions bot
          ref: ${{ steps.set-branch.outputs.branch }} # Checkout the calculated branch
          fetch-depth: 0 # Needed for merge operations

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Vercel CLI
        run: npm install -g vercel

      # Deploy To vercel and output the deployment URL as a GitHub output from the step
      - name: Deploy to Vercel
        id: deploy
        run: |
          DEPLOYMENT_URL=$(vercel deploy \
          --token=${{ secrets.TWIN_VERCEL_TOKEN }} \
          --scope=${{ secrets.TWIN_VERCEL_SCOPE }} \
          --target=${{ steps.set-branch.outputs.branch == 'main' && 'production' || 'dev' }} \
          --force)
          echo "deployment-url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT

      # Use the deployment URL to set an alias for the deployment
      - name: Set Alias
        run: |
          vercel alias set \
          ${{ steps.deploy.outputs.deployment-url }} \
          ${{ steps.set-branch.outputs.branch == 'main' && secrets.DOMAIN_SCHEMA_PROD || secrets.DOMAIN_SCHEMA_DEV }} \
          --token=${{ secrets.TWIN_VERCEL_TOKEN }} \
          --scope=${{ secrets.TWIN_VERCEL_SCOPE }}
